@host = http://localhost:5100

### Criar mês
POST {{host}}/meses
Content-Type: application/json

{
  "label": "Abril 2026"
}

### Listar meses
GET {{host}}/meses

### Criar transação (substitua o mesId pelo Id retornado acima)
@mesId = 4d803bcf-481f-4165-af8a-b8259ba1cab1

POST {{host}}/meses/{{mesId}}/transacoes
Content-Type: application/json

{
  "date": "2026-04-29",
  "description": "Mercado Extra",
  "amount": 350.75
}

### Listar transações do mês
GET {{host}}/meses/{{mesId}}/transacoes
