// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoFinanceiro.Infrastructure.Data;

#nullable disable

namespace ProjetoFinanceiro.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceiroDbContext))]
    [Migration("20260430004807_RenomearTabelasECamposParaPortugues")]
    partial class RenomearTabelasECamposParaPortugues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoFinanceiro.Domain.Entities.BoletoCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("CategoriasBoleto", (string)null);
                });

            modelBuilder.Entity("ProjetoFinanceiro.Domain.Entities.Month", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rotulo");

                    b.HasKey("Id");

                    b.ToTable("Meses", (string)null);
                });

            modelBuilder.Entity("ProjetoFinanceiro.Domain.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PalavraChave");

                    b.Property<int>("Who")
                        .HasColumnType("int")
                        .HasColumnName("Responsavel");

                    b.HasKey("Id");

                    b.ToTable("Regras", (string)null);
                });

            modelBuilder.Entity("ProjetoFinanceiro.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Data");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descricao");

                    b.Property<Guid>("MonthId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MesId");

                    b.Property<int>("Who")
                        .HasColumnType("int")
                        .HasColumnName("Responsavel");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("ProjetoFinanceiro.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("ProjetoFinanceiro.Domain.Entities.Month", null)
                        .WithMany("Transactions")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoFinanceiro.Domain.Entities.Month", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
